AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 55

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'lib/boring_services/services/haproxy.rb'

Metrics/AbcSize:
  Max: 37
  Exclude:
    - 'lib/boring_services/services/memcached.rb'

Metrics/CyclomaticComplexity:
  Max: 12
  Exclude:
    - 'lib/boring_services/services/memcached.rb'

Metrics/PerceivedComplexity:
  Max: 12
  Exclude:
    - 'lib/boring_services/services/memcached.rb'

Metrics/BlockLength:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false


Lint/SuppressedException:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false
